read_data <- function(filepath, data_sheet){
  
  data <- readxl::read_excel(filepath,
                             sheet = data_sheet,
                             col_types = c('guess', #location
                                           'date', #date
                                           'date', #time
                                           'text', #timezone
                                           'text', #method
                                           'text', #characteristic
                                           'numeric', #Value
                                           'text' #unit
                                           ),
                             .name_repair = "universal") |> 
    mutate(Activity_End_Time = Time+ minutes(1)) |> 
    mutate(Time = as.character(format(Time, '%H:%M')),
           Activity_End_Time =  as.character(format(Activity_End_Time, '%H:%M')))
}



summarize_data <- function(input_data){
  
  summarized_data <- input_data |>
    select(-Time, -Activity_End_Time) |> 
    group_by(across(c(-Result.Value))) |> 
    summarise(Result.Value = round(mean(Result.Value),1)) |> 
    ungroup() |> 
    mutate(Time = "0:00",
           Activity_End_Time = "23:59") 
   return(summarized_data)
}




format_data <- function(input_data){
  
  
  data_template <- input_data |> 
    mutate(Date = case_when(Time.zones == "Pacific" ~ ymd(Date, tz =  "America/Los_Angeles"),
                            Time.zones == 'Mountain' ~ ymd(Date, tz =  "America/Boise"))) |> 
    mutate(Date4Id = strftime(Date, format = '%Y%m%d', tz = 'America/Los_Angeles')) |> 
    transmute(ProjectID = 'PWS raw water turbidity',
              Alternate_Project_ID_1 = NA_character_,
              Alternate_Project_ID_2 = NA_character_,
              Monitoring.Location.ID  = Monitoring.Location.ID,
              Activity_Start_Date = as.character(Date),
              Activity_Start_Time = Time,
              Activity_End_Date = as.character(Date),
              Activity_End_Time = Activity_End_Time,
              Activity_Start_End_Time_Zone = case_when(Time.zones == "Pacific" & !dst(Date) ~ "PST (~Nov-Feb)",
                                                       Time.zones == "Pacific" & dst(Date) ~ "PDT (~Mar-Oct)",
                                                       Time.zones == "Mountain" & !dst(Date) ~ "MST (~Nov-Feb)",
                                                       Time.zones == "Mountain" & dst(Date) ~ "MDT (~Mar-Oct)",
              ),
              Activity_Media_Name = "Water",
              Activity_Media_Subdivision_Name = "Surface Water",
              Sample_Tissue_Anatomy	=	NA,
              Biological_Intent	=	NA	,
              Subject_Taxonomic_Name	=	NA,
              Activity_Type	=	 'Sample-Routine',
              `Activity_ID_(Locked)`	=	paste(Monitoring.Location.ID,Date4Id,"SR",sep =":"),
              Sample_Collection_Method	=	 Sample.Collection.Method 	,
              `Top_Depth/Height`	=	NA	,
              `Top_Depth/Height_Unit`	=	NA	,
              `Bottom_Depth/Height`	=	NA	,
              `Bottom_Depth/Height_Unit`	=	NA	,
              Characteristic_Name	=	Characteristic.Name,
              Method_Speciation	=	NA	,
              Result_Sample_Fraction	=	NA	,
              Result_Value	=	 Result.Value 	,
              Result_Unit	=	 Result.Unit 	,
              Result_Value_Type	=	'Actual'	,
              Result_Status_ID	=	'Accepted'	,
              Result_Measure_Qualifier	=	NA	,
              Detection_Limit_Type	=	'Estimated Detection Level'	,
              Detection_Limit_Value	=	1	,
              Detection_Limit_Unit	=	Result.Unit	,
              Reporting_Limit_Type	=	'Minimum Reporting Level'	,
              Reporting_Limit_Value	=	1	,
              Reporting_Limit_Unit	=	Result.Unit	,
              Result_Analytical_Method_ID	=	'2130'	,
              Result_Analytical_Method_Context	=	'APHA'	,
              Laboratory_Name	=	NA	,
              Lab_Sample_ID	=	NA	,
              `Analytical_Start/End_Date`	=	NA	,
              `Analytical_Start/End_Time`	=	NA	,
              `LSP_Start/End_Date`	=	NA	,
              `LSP_Start/End_Time`	=	NA	,
              LSP_Method_ID	=	NA	,
              Lab_Batch_ID	=	NA	,
              Result_Comment	=	NA)	
              
              
              

  
  return(data_template)
  
}

add_comment <- function(input_data){
  
  output <- input_data |> 
    mutate(Result_Comment = "Daily mean value generated by ODEQ")
  
  return(output)
  
}

